
sudo: required

services:
  - docker

before_install:
  - docker build -t navneetnagria/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true navneetnagria/react-test npm test -- --coverage

after success:
  - docker build -t navneetnagria/multi-client ./client

  - docker push navneetnagria/multi-client


