language: generic 

sudo: required
services:
  - docker

before_install:
  - docker build -t navneetnagria/react-test -f ./client/Dockerfile.dev .

script: 
  - docker run -e CI=true navneetnagria/react-test npm test -- --coverage


after success:
  - docker build -t navneetnagria/multi-client ./client
  - docker build -t navneetnagria/multi-nginx ./nginx
  - docker build -t navneetnagria/multi-server ./server
  - docker build -t navneetnagria/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push navneetnagria/multi-client
  - docker push navneetnagria/multi-nginx
  - docker push navneetnagria/multi-server
  - docker push navneetnagria/multi-worker
